Kitten.create(name: 'Fluffy', age: 5, cuteness: 8, softness: 10)
Kitten.create(name: 'Hardnose', age: 7, cuteness: 3, softness: 1)
Kitten.create(name: 'Spot', age: 3, cuteness: 1, softness: 6)
Kitten.create(name: 'Fancy', age: 8, cuteness: 9, softness: 7)
Kitten.create(name: 'Princess', age: 4, cuteness: 10, softness: 10)
